---
- name: Configure Nginx file
  hosts: localhost
  become: yes

  tasks:

    - name: Configure Nginx file
      become: yes
      
      shell: |        
        sleep 10
        
        echo '
          server {
              listen 80;
              listen [::]:80;
              server_name .tk;

              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $http_host;

              location /general {
                  proxy_pass http://ip:31121;
              }
          }
        ' | sudo tee nginx.conf > /dev/null

        sudo mv nginx.conf /etc/nginx/conf.d/nginx.conf
        sudo systemctl restart nginx
        sudo systemctl reload nginx
        sudo systemctl status nginx